version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "multi-player-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXX"
s3_prefix = "multi-player"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev CognitoDomain=multi-player-competition-dev"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "multi-player-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXX"
s3_prefix = "multi-player"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev CognitoDomain=multi-player-competition-dev"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "multi-player-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXX"
s3_prefix = "multi-player"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging CognitoDomain=multi-player-competition-staging"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "multi-player-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXX"
s3_prefix = "multi-player"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod CognitoDomain=multi-player-competition-prod"
